Выполнил задание module2-task1
htmlacademy-javascript/1849247-keksobooking-24 pull request #2
Opened 2021-09-26 21:14 UTC by ifom1500

2021-09-27 07:58 UTC, dtsaryov requested changes

2021-09-27 07:58 UTC, dtsaryov commented on js/main.js
> +  const result = min + Math.random() * (max - min);
Лишняя переменная - сразу верни результат

2021-09-27 07:58 UTC, dtsaryov commented on js/main.js
> +  return roundedNumber;
Целых две лишних переменных

2021-09-27 07:58 UTC, dtsaryov commented on js/main.js
> +const getRandomNumber = (min, max) => {
getRandomFloat

2021-09-27 07:58 UTC, dtsaryov commented on js/main.js
> +const getRandomAnyNumber = (min, max, signsAfterComma = 0) => {
Лишняя функция. Добавь функции getRandomFloat аргумент precision (точность, твой signsAfterComma), и вызывай её из getRandomIntNumber

2021-09-27 15:53 UTC, dtsaryov requested changes

2021-09-27 15:53 UTC, dtsaryov commented on js/main.js
> +  return Math.floor(num * 10 ** precision) / 10 ** precision;
Забыл дописать коммент - используй toFixed:

```JS
Number((Math.random() * (max - min + 1)) + min).toFixed())
```

2021-09-27 15:53 UTC, dtsaryov commented on js/main.js
> +const getRandomIntNumber = (min, max) => getRandomFloat(min, max, 0);
getRandomInt / getRandomInteger

2021-09-27 16:14 UTC, ifom1500 commented on js/main.js
> +  return Math.floor(num * 10 ** precision) / 10 ** precision;
Я умышленно не использовал toFixed так как он работает как метод Math.round(), то есть (цитата из MDN):
```
var numObj = 12345.6789;
numObj.toFixed(1);  // Вернёт '12345.7': обратите внимание на округление
```
А такое округление не совсем подходит в данном случае, так как это может сделать распределение неравномерным. Я думаю, в задании предполагается, что вероятность получения чисел должна быть одинакова. Поэтому предложил вариант с применением Math.floor(), что также советуется в MDN.

2021-09-28 15:40 UTC, dtsaryov approved these changes

2021-09-28 15:40 UTC, merged